.MODEL SMALL
.STACK 100H
.DATA
   INP_MSG DW "ENTER A CHARACTER: $"
.CODE
MAIN PROC

MOV AX, @DATA
MOV DS, AX
    ; INPUT TAKING MESSAGE
    LEA DX, INP_MSG
    MOV AH, 09
    INT 21H
    
    ; READ CHARACTER INPUT
    MOV AH, 1
    INT 21H
    
    ; IF CONDITIONS
    CMP AL, 'A'
    JL EXIT         ; EXIT PROGRAM IF CHARACTER < A
    CMP AL, 'Z'
    JG EXIT         ; EXIT PROGRAM IF CHARACTER > Z
    
    ; ELSE CONDITIONS -> PRINTING THE CHARACTER
    MOV AH, 2       
    MOV DL, AL
    INT 21H
    
    EXIT:
    MOV AX, 4C00H
    INT 21H

MAIN ENDP
END MAIN
