.MODEL SMALL
.STACK 100H
.DATA
    INPUT_MSG db "ENTER A CHARACTER: $"
.CODE
MAIN PROC
;iniitialize DS
MOV AX,@DATA
MOV DS,AX
;enter your code here
    ; PRINTING INPUT MESSAGE
    LEA DX, INPUT_MSG
    MOV AH, 9
    INT 21H
    
    ; TAKING INPUT
    MOV AH, 1
    INT 21H
    
    ; STORING THE CHARACTER IN BL
    MOV BL, AL
    
    ; PRINTING OUTPUT AFTER MESSAGE
    MOV DL, BL
    MOV AH, 02
    INT 21H

;exit to DOS
MOV AX,4C00H
INT 21H
MAIN ENDP
END MAIN