.MODEL SMALL
.STACK 100H
.DATA
    INPUT_MSG DB "ENTER A HEX DIGIT(A-F): $"
    OUTPUT_MSG DB "IN DECIMAL IT IS: $"
.CODE
MAIN PROC
    ; INITIALIZE DS
    MOV AX, @DATA
    MOV DS, AX
    
    ; PRINTING INPUT MESSAGE
    LEA DX, INPUT_MSG
    MOV AH, 9
    INT 21H
    
    ; TAKING INPUT FOR HEX DIGIT
    MOV AH, 1
    INT 21H
    MOV BL, AL
    SUB BL, 17
    
    ; POSITIONING THE CURSOR
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ; PRINTING OUTPUT MESSAGE
    LEA DX, OUTPUT_MSG
    MOV AH, 9
    INT 21H
    
    ; PRINTING OUTPUT
    MOV DL, 49
    MOV AH, 2
    INT 21H
    
    MOV DL, BL
    MOV AH, 2
    INT 21H
    
    ; EXIT TO DOS
    MOV AX, 4C00H
    INT 21H
MAIN ENDP
END MAIN
