.MODEL SMALL
.STACK 100H
.DATA
    INPUT_MSG db "ENTER A UPERCASE LETTER: $"
    OUTPUT_MSG db "LOWERCASE LETTER IS: $"
.CODE
MAIN PROC
;iniitialize DS
MOV AX,@DATA
MOV DS,AX
;enter your code here
    ; PRINTING INPUT MESSAGE
    LEA DX, INPUT_MSG
    MOV AH, 9
    INT 21H
    
    ; TAKING INPUT
    MOV AH, 1
    INT 21H
    
    ; CONVERTING TO LOWERCASE LETTER
    ADD AL, 32
    MOV BL, AL
    
    ; POSITIONING THE CURSOR
    MOV AH, 02
    MOV DL, 0DH
    INT 21H
    
    MOV DL, 0AH
    INT 21H
    
    ; PRINTING OUTPUT MESSAGE
    LEA DX, OUTPUT_MSG
    MOV AH, 09
    INT 21H
    
    ; PRINTING OUTPUT AFTER MESSAGE
    MOV DL, BL
    MOV AH, 02
    INT 21H

;exit to DOS
MOV AX,4C00H
INT 21H
MAIN ENDP
END MAIN